# Generated by Django 5.2.6 on 2025-09-23 09:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_order_amount_alter_order_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 23, 9, 20, 25, 654919, tzinfo=datetime.timezone.utc)),
        ),
    ]
