# Generated by Django 5.2.6 on 2025-09-23 09:50

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_order_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 23, 9, 50, 52, 690010, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='order_items',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='cart.order'),
        ),
    ]
