# Generated by Django 5.2.6 on 2025-09-24 04:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_alter_order_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 24, 4, 38, 7, 93053, tzinfo=datetime.timezone.utc)),
        ),
    ]
